---
# install tasks file for blinkstick

#-------------------------------------------------
# Setup Dirs
#-------------------------------------------------

- name: Ensure bin dir exists for the scripts
  file:
    path: bin
    mode: 0755
    state: directory

#-------------------------------------------------
# Override default vars when monitor group exists
#-------------------------------------------------

# The following section will override the default 
# vars with ones defined in group/host vars on
# the monitor group (where zabbix is).

- name: Override zabbix_url
  set_fact: 
    zabbix_url: "{{ hostvars[item]['zabbix_url'] }}"
  with_items:
    - "{{ groups['monitor'][0] }}"
  when: "groups['monitor'][0] is defined"

- name: Override zabbix_username
  set_fact: 
    zabbix_username: "{{ hostvars[item]['zabbix_username'] }}"
  with_items:
    - "{{ groups['monitor'][0] }}"
  when: "groups['monitor'][0] is defined"

- name: Override zabbix_password
  set_fact: 
    zabbix_password: "{{ hostvars[item]['zabbix_password'] }}"
  with_items:
    - "{{ groups['monitor'][0] }}"
  when: "groups['monitor'][0] is defined"

#-------------------------------------------------
# Upload Template Script
#-------------------------------------------------

- name: Install blinkstick-zabbix script
  template:
    src: blinkstick-poll-zabbix.sh.j2
    dest: "{{ ansible_user_dir }}/bin/blinkstick-poll-zabbix.sh"
    mode: 0755

- name: Install blinkstick-blank script
  template:
    src: blinkstick-blank.sh.j2
    dest: "{{ ansible_user_dir }}/bin/blinkstick-blank.sh"
    mode: 0755

- name: Install zabbix-trigger check script
  template:
    src: zab-check.sh.j2
    dest: "{{ ansible_user_dir }}/bin/zab-check.sh"
    mode: 0755

#-------------------------------------------------
# Add Cronjobs
#-------------------------------------------------

- name: Setup Crontab Entries
  cron:
    name: "Update BlinkStick LEDs"
    job: "{{ ansible_user_dir }}/bin/blinkstick-poll-zabbix.sh &> /dev/null"
